version: '3.8'

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      target: dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql  # 這裡的 mysql 是指 mysql 服務的名稱
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mysql-data:/var/lib/mysql  # 設定数据卷儲存位置
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

